-- 코드를 입력하세요
WITH M AS (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME = 'Milk'
), Y AS (SELECT CART_ID
         FROM CART_PRODUCTS
         WHERE NAME = 'Yogurt'
)

SELECT Y.CART_ID
FROM Y
INNER JOIN M
ON Y.CART_ID = M.CART_ID
ORDER BY CART_ID