-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT) * p.PRICE AS SALES
FROM PRODUCT AS p
JOIN OFFLINE_SALE AS o
ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE;