-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM ( SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
      ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS TYPE_RANK
      FROM REST_INFO) AS REST_RANK
WHERE TYPE_RANK = 1
ORDER BY FOOD_TYPE DESC;