-- 코드를 작성해주세요

WITH RANKED_ECOLI AS (
    SELECT
        ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_GROUP
    FROM
        ECOLI_DATA
)

SELECT 
    R.ID,
    CASE
        WHEN R.COLONY_GROUP = 1 THEN 'CRITICAL'
        WHEN R.COLONY_GROUP = 2 THEN 'HIGH'
        WHEN R.COLONY_GROUP = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    RANKED_ECOLI R
ORDER BY
    R.ID ASC;
