WITH RENTAL_HISTORY AS (
    SELECT *
         , CASE
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
               ELSE '90일 이상'
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), TRUCKS AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID, ROUND(IF(P.DURATION_TYPE IS NULL,
                             T.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1),
                             T.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - P.DISCOUNT_RATE/100))) AS FEE
FROM TRUCKS T
INNER JOIN RENTAL_HISTORY H
ON T.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC