#2022-04-13이고 MCDP_CD가 CS 이고 APNT_CNCL_YN이 N인
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE A.APNT_YMD LIKE '2022-04-13%' 
AND A.MCDP_CD = 'CS' 
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD
