WITH FRONT_END_MASK AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, FRONT_END_MASK F
WHERE 
    D.SKILL_CODE & F.CODE > 0
ORDER BY D.ID