-- 코드를 입력하세요
SELECT b.WRITER_ID AS USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_USER AS u
ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING SUM(PRICE) >= 700000 
ORDER BY TOTAL_PRICE;