-- 코드를 작성해주세요
WITH GRADE_TB AS (
    SELECT EMP_NO,
        CASE
            WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT GT.EMP_NO, HE.EMP_NAME, GT.GRADE,
    CASE
        WHEN GT.GRADE = 'S' THEN HE.SAL * 0.2
        WHEN GT.GRADE = 'A' THEN HE.SAL * 0.15
        WHEN GT.GRADE = 'B' THEN HE.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM GRADE_TB GT
JOIN HR_EMPLOYEES HE ON GT.EMP_NO = HE.EMP_NO
ORDER BY GT.EMP_NO
