SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    -- PARTITION BY로 연도별 그룹을 만들고, 그 그룹 안에서 최댓값을 구합니다.
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
ORDER BY
    YEAR, YEAR_DEV;