-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;

SELECT CATEGORY,PRICE,PRODUCT_NAME
FROM  FOOD_PRODUCT
WHERE (CATEGORY , PRICE ) IN
   (SELECT CATEGORY , max(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' or  CATEGORY = '국' or   CATEGORY = '김치'or CATEGORY = '식용유'  
    GROUP BY CATEGORY)
    ORDER BY PRICE DESC;