WITH FRONT_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
DEVELOPERS_GRADES AS (
    SELECT D.ID, D.EMAIL,
    CASE
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0
        AND  (D.SKILL_CODE & F.CODE) > 0 THEN 'A'
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
        WHEN (D.SKILL_CODE & F.CODE) > 0 THEN 'C'
        ELSE NULL
    END AS GRADE
    FROM DEVELOPERS D, FRONT_CODE F
)

SELECT GRADE, ID, EMAIL
FROM DEVELOPERS_GRADES
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID